# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=100)),
                ('review_description', models.TextField(max_length=200)),
                ('review_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('review_views', models.IntegerField(default=0)),
            ],
        ),
    ]
