# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopreview',
            name='reviewer_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
